### ISSUE TITLE
liunx x86架构下，权限777运行程序报错，还有ws的正向代理地址设置多少

### ISSUE THREAD

**Issue by wodehijieaas** [ilyfairy/DstQueryBot#2]
/mnt/sda1/DstQueryBot-master] # ./DstQueryBot-linux-x64
-bash: ./DstQueryBot-linux-x64: cannot execute: required file not found
/mnt/sda1/DstQueryBot] # ./DstQueryBot-linux-x64
-bash: ./DstQueryBot-linux-x64: cannot execute: required file not found

**Comment by ilyfairy** [comment]
.net5+貌似不支持编译linux-x86, 只能想办法用linux-x64的系统了
正向ws地址在gocqhttp的配置文件里, `config.yaml`, 默认是 `ws://127.0.0.1:6700`
